### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by luilver** [runtipi/cli#24]
Following installation steps fails:

<details>
error: linker `cc` not found<br>
  |<br>
  = note: No such file or directory (os error 2)<br>

<br>error: could not compile `proc-macro2` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `libc` (build script) due to 1 previous error
</details>

#### OS
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

#### Rust
rustc 1.76.0 (07dca489a 2024-02-04)

#### Dependencies
cc?

**Comment by luilver** [comment]
Solution:

```
sudo apt install build-essential
```

**Comment by jnth** [comment]
The building process create a file named `VERSION` in `src/assets`.
If you build `runtipi-cli` from source, create a `VERSION` like this:

```
echo "dev" > src/assets/VERSION
```

**Comment by steveiliop56** [comment]
Closing this - The CLI is now built from the ground up with Go so the issues do not apply.
