### ISSUE TITLE
[BUG] error message when using runtipi-cli app start-all

### ISSUE THREAD

**Issue by falkheiland** [runtipi/cli#35]
### Checklist
Before opening your issue be sure to have completed all those tasks.
- [x] My issue is not related to an app I installed through tipi (If so please open your issue here: https://github.com/runtipi/runtipi-appstore/issues)
- [x] My issue is not a support request (eg: "My instance is not running after update". If so please ask for support in the help section of our [Discord server](https://discord.gg/gyeHhmvwaK))
- [x] I have searched for an already existing issue with similar context and errors. My issue has not yet been reported.
- [x] I have included a clear description and steps to reproduce.
- [x] I have included logs from the file `runtipi/logs/error.log` if relevant

**Describe the bug**
there is an error on the cli when using `sudo ./runtipi-cli app start-all` 

```
sudo ./runtipi-cli app start-all
Welcome to Runtipi CLI ✨

⠴ Starting all apps...
thread 'main' panicked at src/commands/app.rs:161:80:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: None, path: "/worker-api/apps/start-all", query: None, fragment: None }, source: TimedOut }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

All apps are still being started.

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - Tipi Version 3.0.3

**Comment by meienberger** [comment]
Most probably your instance was not running properly, I added better error handling and messages
